# Generated by Django 5.2.8 on 2025-12-07 00:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('Consumidor', 'Consumidor'), ('Gerador', 'Gerador')], max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=20)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id_residente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telemovel', models.CharField(max_length=20, unique=True)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Agua', 'Água'), ('Luz', 'Luz'), ('Gas', 'Gás')], max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo_residente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(choices=[('m3', 'Metro Cúbico (m³)'), ('kWh', 'Kilowatt-hora (kWh)')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.categoria')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.residente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.tipo')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='FornecedorTipo',
            fields=[
                ('id_fornecedor_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(choices=[('m3', 'Metro Cúbico (m³)'), ('kWh', 'Kilowatt-hora (kWh)')], max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.fornecedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.tipo')),
            ],
            options={
                'verbose_name': 'Serviço do Fornecedor',
                'verbose_name_plural': 'Serviços dos Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='FornecedorValor',
            fields=[
                ('id_fornecedor_valor', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fornecedor_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.fornecedortipo')),
            ],
            options={
                'verbose_name': 'Tarifa / Preço',
                'verbose_name_plural': 'Histórico de Tarifas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegistoConsumo',
            fields=[
                ('id_registo_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.dispositivo')),
            ],
            options={
                'verbose_name': 'Registo de Consumo',
                'verbose_name_plural': 'Registos de Consumo',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorResidente',
            fields=[
                ('id_fornecedor_residente_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1)),
                ('fornecedor_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.fornecedortipo')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.residente')),
            ],
            options={
                'verbose_name': 'Contrato de Residente',
                'verbose_name_plural': 'Contratos de Residentes',
            },
        ),
        migrations.CreateModel(
            name='Orcamento_limite',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.residente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestao_Consumos.tipo')),
            ],
            options={
                'verbose_name': 'Orçamento / Limite',
                'verbose_name_plural': 'Orçamentos e Limites',
                'unique_together': {('residente', 'tipo', 'timestamp')},
            },
        ),
    ]
